### ISSUE TITLE
S/4HANA 1909 or 2020

### ISSUE THREAD

**Issue by busetde** [GoogleCloudPlatform/sap-deployment-automation#2]
Hi,

Is it possible to have SAP deployment automation supported for SAP S/4HANA 1909 or 2020?

Thanks - Budi

**Comment by rjosephwright** [comment]
Hi @busetde, I don't think anyone has tested it yet but it would be great to have support for additional platforms.

**Comment by busetde** [comment]
Hi @rjosephwright,
Yes it would be great to have support for SAP S/4HANA 1909, 2020 as this is the latest version that customer would like to deploy.
By any chance do you have advise on what need to be change from current code if partner / customer would like to try their own to deploy 1909 or 2020?

Thanks - Budi

**Comment by balaguduru** [comment]
@busetde We are currently in the process of testing the code for 1909 and 2020 and add any updates required. Should have an update on this shortly. In the meantime feel free to try out the code with the latest versions by pointing to the right install files.

**Comment by busetde** [comment]
@rjosephwright - I've already clone the latest commit and saw there's 1909 and 2020 in the survey_spec.json [1] but when I've done the bootstrap and check again the survey_spec.json there's no 1909 and 2020 [2]. 
Could you please kindly advise, as I'm confuse why it's not there in the AWX instance?

[1] 
![awx1](https://user-images.githubusercontent.com/63712632/128341543-37b7f916-19b5-4876-aa51-7dba095c2182.png)
[2]
![awx2](https://user-images.githubusercontent.com/63712632/128341559-8f929a3e-cc71-4a05-ae0f-9748526a440c.png)

Thanks - Budi

**Comment by busetde** [comment]
@rjosephwright - thanks for the updates. It's working now.
