### ISSUE TITLE
PD - Balanced not listed as an options

### ISSUE THREAD

**Issue by busetde** [GoogleCloudPlatform/sap-deployment-automation#22]
Hi,

From below:
terraform/modules/hana-scaleup/locals.tf
Looks like there's no PD-Balanced supported for deployment
but from documentation PD-Balanced supported with certain sizes:
https://cloud.google.com/solutions/sap/docs/sap-hana-planning-guide#minimum_sizes_for_ssd-based_persistent_disks

Could you please kindly advise whether PD-Balanced will be supported for deployment?

Thanks - Budi

**Comment by balaguduru** [comment]
@busetde PD-Balanced is now supported for HANA.
