### ISSUE TITLE
sap_hana_subnetwork is missing

### ISSUE THREAD

**Issue by tstaerk** [GoogleCloudPlatform/sap-deployment-automation#44]
I tried to run the installation for NetWeaver-Distributed and I got an error message that the HANA subnetwork has not been defined. Please add 

sap_hana_subnetwork:

to sap-deployment-automation/stacks/NetWeaver-Distributed/vars/deploy-vars.yml

**Comment by balaguduru** [comment]
Done. Pushed the update. Thank you for trying out the code and providing feedback.

**Comment by tstaerk** [comment]
wow, I am impressed by your speed and feedback culture :)

**Comment by tstaerk** [comment]
For the records: https://github.com/GoogleCloudPlatform/sap-deployment-automation/commit/f7bf8e20d3f9c34dcf4a1414ebd5855e09ee46da#diff-503583ce7a7d55da992e48380f17a43e4922b5aac64e1965f3d8ca4e6ac29b47
