### ISSUE TITLE
Error installing python-pip on sles-15-sp2-sap

### ISSUE THREAD

**Issue by Robby29** [GoogleCloudPlatform/sap-deployment-automation#56]
I am trying to the HANA-HA stack and I get the below error in one of the playbook tasks.

**OS:** sles-15-sp2-sap
**Stack:** HANA-HA
**Role:** base
**Task:** os.yml
**Step:** Install packages
**Package list for suse_15**
  - acl
  - libopenssl1_1
  - tuned
  - krb5-32bit
  - unrar
  - numactl
  - sap-suse-cluster-connector
  - socat
  - libgcc_s1
  - libstdc++6
  - libatomic1
  - python-pip
  - python3-pip

**Error**: 
`fatal: [10.160.0.12]: FAILED! => {"attempts": 50, "changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+acl", "+krb5-32bit", "+unrar", "+numactl", "+libatomic1", "+python-pip", "+python3-pip", "+libstdc++6-32bit", "+pam-32bit"], "msg": "Package '+python-pip' not found.", "rc": 104, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<message type=\"error\">Package &apos;+python-pip&apos; not found.</message>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<message type=\"error\">Package &apos;+python-pip&apos; not found.</message>", "</stream>"]}`

**My Analysis**: Looks like python-pip is not available with sles-15-sp2-sap. However python3-pip is installing just fine. The task is getting timed out after expected number of attempts. We either need to add the corresponding repository for python-pip or put a condition to exclude this for sles15 versions.

**Comment by rjosephwright** [comment]
Hi Robby, most likely the guest registration didn't complete so the machine doesn't have all of the repos configured. As a workaround, you can log into the machine and run `registercloudguest --force-new` and then rerun the playbook. I have opened a [PR](https://github.com/GoogleCloudPlatform/sap-deployment-automation/pull/57) to make this more reliable by waiting for guest registration to complete before attempting to install packages, as this is a common problem on SLES 15.

**Comment by Robby29** [comment]
Thanks @rjosephwright. Sounds good.
