### ISSUE TITLE
where to get these install media listed in this repo?

### ISSUE THREAD

**Issue by m9999m** [GoogleCloudPlatform/sap-deployment-automation#78]
Dear All,

I am planning to setup an environment by following "[sap-deployment-automation](https://github.com/GoogleCloudPlatform/sap-deployment-automation)". It requires the install media listed here [sap-deployment-automation/docs/install-media.md]

My question is where to get these install media?

Thank you

**Comment by placed87** [comment]
Hello,
software needs to be downloaded from SAP website https://launchpad.support.sap.com/#/softwarecenter

**Comment by balaguduru** [comment]
Agree with @placed87
