### ISSUE TITLE
Package &apos;+krb5-32bit&apos; not found.

### ISSUE THREAD

**Issue by tstaerk** [GoogleCloudPlatform/sap-deployment-automation#87]
Trying to install HANA-HA with SLES12 and SLES15, I get the error message:

fatal: [10.132.0.3]: FAILED! => {"attempts": 50, "changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+acl", "+krb5-32bit", "+unrar", "+numactl", "+sap-suse-cluster-connector", "+socat", "+libatomic1", "+python-pip", "+python3-pip", "+libstdc++6-32bit", "+pam-32bit"], "msg": "No provider of '+unrar' found.", "rc": 104, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<message type=\"error\">Package &apos;+krb5-32bit&apos; not found.</message>\n<message type=\"error\">Package &apos;+libstdc++6-32bit&apos; not found.</message>\n<message type=\"error\">Package &apos;+pam-32bit&apos; not found.</message>\n<message type=\"error\">Package &apos;+python3-pip&apos; not found.</message>\n<message type=\"error\">No provider of &apos;+acl&apos; found.</message>\n<message type=\"error\">No provider of &apos;+numactl&apos; found.</message>\n<message type=\"error\">No provider of &apos;+libatomic1&apos; found.</message>\n<message type=\"error\">No provider of &apos;+python-pip&apos; found.</message>\n<message type=\"error\">No provider of &apos;+sap-suse-cluster-connector&apos; found.</message>\n<message type=\"error\">No provider of &apos;+socat&apos; found.</message>\n<message type=\"error\">No provider of &apos;+unrar&apos; found.</message>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<message type=\"error\">Package &apos;+krb5-32bit&apos; not found.</message>", "<message type=\"error\">Package &apos;+libstdc++6-32bit&apos; not found.</message>", "<message type=\"error\">Package &apos;+pam-32bit&apos; not found.</message>", "<message type=\"error\">Package &apos;+python3-pip&apos; not found.</message>", "<message type=\"error\">No provider of &apos;+acl&apos; found.</message>", "<message type=\"error\">No provider of &apos;+numactl&apos; found.</message>", "<message type=\"error\">No provider of &apos;+libatomic1&apos; found.</message>", "<message type=\"error\">No provider of &apos;+python-pip&apos; found.</message>", "<message type=\"error\">No provider of &apos;+sap-suse-cluster-connector&apos; found.</message>", "<message type=\"error\">No provider of &apos;+socat&apos; found.</message>", "<message type=\"error\">No provider of &apos;+unrar&apos; found.</message>", "</stream>"]}
fatal: [10.132.0.2]: FAILED! => {"attempts": 50, "changed": false, "cmd": ["/usr/bin/zypper", "--quiet", "--non-interactive", "--xmlout", "install", "--type", "package", "--auto-agree-with-licenses", "--no-recommends", "--", "+acl", "+krb5-32bit", "+unrar", "+numactl", "+sap-suse-cluster-connector", "+socat", "+libatomic1", "+python-pip", "+python3-pip", "+libstdc++6-32bit", "+pam-32bit"], "msg": "No provider of '+unrar' found.", "rc": 104, "stderr": "", "stderr_lines": [], "stdout": "<?xml version='1.0'?>\n<stream>\n<message type=\"error\">Package &apos;+krb5-32bit&apos; not found.</message>\n<message type=\"error\">Package &apos;+libstdc++6-32bit&apos; not found.</message>\n<message type=\"error\">Package &apos;+pam-32bit&apos; not found.</message>\n<message type=\"error\">Package &apos;+python3-pip&apos; not found.</message>\n<message type=\"error\">No provider of &apos;+acl&apos; found.</message>\n<message type=\"error\">No provider of &apos;+numactl&apos; found.</message>\n<message type=\"error\">No provider of &apos;+libatomic1&apos; found.</message>\n<message type=\"error\">No provider of &apos;+python-pip&apos; found.</message>\n<message type=\"error\">No provider of &apos;+sap-suse-cluster-connector&apos; found.</message>\n<message type=\"error\">No provider of &apos;+socat&apos; found.</message>\n<message type=\"error\">No provider of &apos;+unrar&apos; found.</message>\n</stream>\n", "stdout_lines": ["<?xml version='1.0'?>", "<stream>", "<message type=\"error\">Package &apos;+krb5-32bit&apos; not found.</message>", "<message type=\"error\">Package &apos;+libstdc++6-32bit&apos; not found.</message>", "<message type=\"error\">Package &apos;+pam-32bit&apos; not found.</message>", "<message type=\"error\">Package &apos;+python3-pip&apos; not found.</message>", "<message type=\"error\">No provider of &apos;+acl&apos; found.</message>", "<message type=\"error\">No provider of &apos;+numactl&apos; found.</message>", "<message type=\"error\">No provider of &apos;+libatomic1&apos; found.</message>", "<message type=\"error\">No provider of &apos;+python-pip&apos; found.</message>", "<message type=\"error\">No provider of &apos;+sap-suse-cluster-connector&apos; found.</message>", "<message type=\"error\">No provider of &apos;+socat&apos; found.</message>", "<message type=\"error\">No provider of &apos;+unrar&apos; found.</message>", "</stream>"]}

This happens during the step TASK [base : Install packages].
I call the command ./ansible-wrapper ./stacks/HANA-HA/playbook.yml --extra-vars '@./stacks/HANA-HA/vars/deploy-vars.yml
The deploy-vars.yml file looks like this:

# Terraform common vars for hana and netweaver (optional)
sap_primary_zone: europe-west1-b
sap_secondary_zone: europe-west1-c

# Ansible/Terraform common vars for hana and netweaver (required)
sap_project_id: thorstenstaerk-terraform
sap_tf_state_bucket: thorstenstaerk-hana
sap_source_image_family: sles-15-sp1-sap
sap_source_image_project: suse-sap-cloud
sap_hana_subnetwork: vpc1
sap_subnetwork_project_id: thorstenstaerk-terraform
sap_tf_state_bucket_prefix: hanaha

# Terraform hana variables (required)
# Instance name should be 7 charecters or less
sap_hana_instance_name: hanslbg
sap_hana_service_account_name: sap-common-sa

# Terraform hana variables (optional)
sap_hana_instance_type: n1-highmem-32
sap_hana_autodelete_boot_disk: "true"
sap_hana_boot_disk_size: 30
sap_hana_boot_disk_type: pd-ssd
sap_hana_additional_disk_type: pd-balanced
sap_hana_network_tags: ["sap-allow-all"]
sap_hana_target_instance_size: 1
sap_hana_pd_kms_key: null
sap_hana_create_backup_volume: true
sap_hana_backint_install: false
sap_hana_fast_restart: false

# Ansible hana variables (required)
sap_hana_password: Abcde123

**Comment by tstaerk** [comment]
Would it be possible to find out what this step is actually doing so I could reproduce manually?

**Comment by tstaerk** [comment]
There was no internet connection. Is it somehow possible to adapt the error message or check for the internet connection?

**Comment by tstaerk** [comment]
with internet connection, same error. Unrar is not to be found in yast2 and zypper lr does not list any repository.

**Comment by balaguduru** [comment]
@tstaerk There is fix for the issue which was tested recently. Using `Zypper` to install packages and setting the `update_cache` to true seems to have solved the problem. Also proper SUSE registration needs to happen before to have all the right repos activated so the packages can be discovered and installed by zypper. Will push that fix soon after the testing.

**Comment by tstaerk** [comment]
very cool, I thought I was the only one with this issue. Thanks!

**Comment by tstaerk** [comment]
OK, in order to check if this works now, I created a new project tstaerk-tf-3, enabled compute engine API, created an auto-mode network vpc1, set up cloud NAT, created a cloud router in us-central1, created a bastion host called bastion with SLES15 as OS and read/write API access as well to Compute Engine as to Cloud Storage.

**Comment by tstaerk** [comment]
Then I created a service account sap-common-sa. Made it storage admin of the bucket thorstenstaerk-hana.

**Comment by tstaerk** [comment]
I am describing here how I test your fix.

**Comment by balaguduru** [comment]
@tstaerk ... In your forked/cloned repo replace the code in the file `https://github.com/GoogleCloudPlatform/sap-deployment-automation/blob/master/ansible/roles/base/tasks/os.yml` from L27 - L34 with the following. Make sure SUSE registration is successful and you see the mirrors so ansible can find and install packages.

```
- name: Install RedHat packages
  package:
    name: "{{ package_list }}"
    state: present
  register: result
  retries: "{{ package_retries_cnt }}"
  until: result is succeeded
  delay: "{{ package_retries_delay }}"
  when: ansible_os_family == 'RedHat'

- name: Install Suse packages
  zypper:
    name: "{{ item }}"
    state: present
    update_cache: yes
  register: result
  retries: "{{ package_retries_cnt }}"
  until: result is succeeded
  delay: "{{ package_retries_delay }}"
  when: ansible_os_family == 'Suse'
  with_items: "{{ package_list }}"
```

This fix will go into the code base in the next release.

**Comment by tstaerk** [comment]
Hi,

I had to re-check-out the repo. There is no folder blob beneath sap-deployment-automation
