### ISSUE TITLE
Reset / destroy implementation

### ISSUE THREAD

**Issue by placed87** [GoogleCloudPlatform/sap-deployment-automation#88]
Hello,
I would like to know how to destroy every object created with a terraform deploy using this repository

For exmaple I run
./ansible-wrapper stacks/SAP-Prerequisites/playbook.yml -e @stacks/SAP-Prerequisites/vars/deploy-vars.yml
./ansible-wrapper stacks/WebDisp/playbook.yml -e @stacks/WebDisp/vars/deploy-vars.yml

How can I remove everything after the deploy?

Thank you

**Comment by balaguduru** [comment]
@placed87 .. You can append this additional argument `-e state=absent` to your stack deploy command to delete any stack and that destroys the infra of the stack. This argument essentially points to running `terraform destroy` by ansible. 

**example:**
./ansible-wrapper stacks/SAP-Prerequisites/playbook.yml -e @stacks/SAP-Prerequisites/vars/deploy-vars.yml -e state=absent
