### ISSUE TITLE
Hardcoded Credential

### ISSUE THREAD

**Issue by SlimTrabelsi** [GoogleCloudPlatform/sap-deployment-automation#9]
Hi,
It seems that you left a clear text credential here https://github.com/GoogleCloudPlatform/sap-deployment-automation/blob/4f56409825f69613cce8f9604b8e97d7bd72e039/stacks/HANA-HA/vars/deploy-vars.yml#L45

Thank you

**Comment by SlimTrabelsi** [comment]
Also here https://github.com/GoogleCloudPlatform/sap-deployment-automation/blob/501e663427c4d1c862f362453193869233d2024e/stacks/netweaver-aas-ha/vars/deploy-vars.yml#L64

**Comment by balaguduru** [comment]
@SlimTrabelsi Thank you for pointing it. The default password is specified in clear text on purpose. This provides the flexibility  for anyone using the code to expand its capability to integrate with a secrets management tool/service. And it is advised to change the default password to the password of your choice before any deployment. Also `ansible-vault` can help with encrypting secrets data as well.

**Comment by SlimTrabelsi** [comment]
Thank you for the reply
