### ISSUE TITLE
Forminator Syntax error in Netweaver Standard Stack

### ISSUE THREAD

**Issue by vasu2809** [GoogleCloudPlatform/sap-deployment-automation#90]
Hi,

Why is the playbook.yml file not containing a name tag for forminator? While all other stacks contain '- name:'

I noticed this when I was trying to deploy NetWeaver-Standard stack and ran into this issue

Then I appended the piece of code in playbook.yml **- name: SAP NW deploy** but I still get the below issue when trying to deploy NW-Standard 

**ERROR! the role 'forminator' was not found in /sap-deployment-automation/stacks/NetWeaver-Standard/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/sap-deployment-automation/stacks/NetWeaver-Standard

The error appears to be in '/sap-deployment-automation/stacks/NetWeaver-Standard/playbook.yml': line 18, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
  - role: forminator
    ^ here**

**Comment by balaguduru** [comment]
The error is related to missing path to the ansible roles. Exporting the `ANSIBLE_CONFIG` var by pointing to the `ansible.cfg `file will fix the issue.
